services:
  dumb:
    container_name: dumb
    image: ghcr.io/shindouj/dumb:latest
    network_mode: service:cloudflare
    restart: unless-stopped
    user: nobody
    read_only: true
    tmpfs:
      - /app/.next/cache/:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  dumb:
