services:
  dumb:
    container_name: dumb
    image: ghcr.io/shindouj/dumb:latest
    restart: unless-stopped
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  dumb:
